#pragma once

#include "core/types.hpp"

#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

namespace trading::execution {

// Stores the configurable behavior of the simulated execution engine.
struct SimulatedExecutionConfig {
    double partial_fill_threshold {0.0};
    double partial_fill_ratio {0.0};
};

// Stores the lifecycle output generated by one execution action.
struct ExecutionResult {
    std::string order_id;
    std::string client_order_id;
    std::vector<trading::core::OrderUpdate> updates;
    std::vector<trading::core::FillEvent> fills;
};

// Simulates a deterministic execution venue for development and tests.
class SimulatedExecutionEngine {
public:
    explicit SimulatedExecutionEngine(SimulatedExecutionConfig config) : config_(config) {}

    // Submits one order request and returns the initial lifecycle events.
    [[nodiscard]] ExecutionResult submit(const trading::core::OrderRequest& request);

    // Completes an open partially-filled order and returns the final lifecycle events.
    [[nodiscard]] ExecutionResult complete_open_order(const std::string& order_id);

    // Cancels an open partially-filled order and returns the cancel lifecycle events.
    [[nodiscard]] ExecutionResult cancel_open_order(const std::string& order_id);

    // Restores one partially-complete open order during startup recovery.
    void restore_open_order(const std::string& order_id,
                            const std::string& client_order_id,
                            const trading::core::OrderRequest& request,
                            double filled_quantity);

private:
    struct OpenOrderState {
        trading::core::OrderRequest request;
        std::string client_order_id;
        double filled_quantity {0.0};
    };

    [[nodiscard]] double clamp_partial_fill_ratio() const;
    [[nodiscard]] trading::core::OrderUpdate make_update(const std::string& order_id,
                                                         const std::string& client_order_id,
                                                         trading::core::OrderStatus status,
                                                         double filled_quantity,
                                                         std::optional<std::string> reason = std::nullopt) const;

    SimulatedExecutionConfig config_;
    std::unordered_map<std::string, OpenOrderState> open_orders_;
    std::size_t next_order_id_ {1};
    std::size_t next_client_order_id_ {1};
    std::size_t next_fill_id_ {1};
};

}  // namespace trading::execution
